name:                cardano-coin-selection
version:             1.0.1
github:              IntersectMBO/cardano-coin-selection
license:             Apache-2.0
author:              Intersect MBO
maintainer:          operations@iohk.io
copyright:           2024 Intersect MBO
synopsis:            Algorithms for coin selection and fee balancing.
category:            Cardano

extra-source-files:
- ChangeLog.md

description: |
  Please see the README on GitHub at <https://github.com/IntersectMBO/cardano-coin-selection>

dependencies:
- base >= 4.7 && < 5

flags:
  release:
    description: Compile executables for a release.
    default: False
    manual: True

library:
  source-dirs:
  - src/library
  - src/internal
  ghc-options:
  - -Wall
  - -Wcompat
  - -fwarn-redundant-constraints
  when:
  - condition: flag(release)
    ghc-options:
    - -Werror
  default-extensions:
  - NoImplicitPrelude
  dependencies:
  - bytestring
  - containers
  - cryptonite
  - deepseq
  - quiet
  - text
  - transformers >= 0.5.6.0

tests:
  unit:
    source-dirs: src/test
    main: Spec.hs
    default-extensions:
    - NoImplicitPrelude
    ghc-options:
    - -Wall
    - -Wcompat
    - -fwarn-redundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    when:
    - condition: flag(release)
      ghc-options:
      - -Werror
    dependencies:
    - QuickCheck
    - bytestring
    - cardano-coin-selection
    - containers
    - cryptonite
    - deepseq
    - fmt
    - hspec
    - memory
    - quiet
    - random
    - text
    - transformers >= 0.5.6.0
    - vector
